#Edit the Player Roles
clans:
  DUMMY:
    08944516-039d-4b71-a969-7dafaffd5b39: Dummy

söldner:
  08944516-039d-4b71-a969-7dafaffd5b39: Dummy

spectator:
  08944516-039d-4b71-a969-7dafaffd5b39: Dummy

#Edits for the Game
gameisactive: false
worldborderradius: 32

#Edit the Flag Holder
flagholder: af9952ca-590a-47d5-8867-d0f4a1871af2

#Whitelist
whitelist: true

#Edit the Effects
clanFlagHolderEffects:
  speed: 0
  haste: 1
  strength: 0
  jump_boost: 0
  regeneration: 0
  resistance: 0
  health_boost: 0
  luck: 0
  dolphins_grace: 0
  hero_of_the_village: 0

  slowness: 1
  weakness: 1
  bad_luck: 2

clanMemberEffects:
  speed: 1
  haste: 1
  strength: 0
  jump_boost: 0
  regeneration: 0
  resistance: 0
  health_boost: 0
  luck: 2
  dolphins_grace: 0
  hero_of_the_village: 2

  slowness: 0
  weakness: 0
  bad_luck: 0

söldnerEffects:
  speed: 1
  haste: 1
  strength: 0
  jump_boost: 0
  regeneration: 0
  resistance: 1
  health_boost: 2
  luck: 2
  dolphins_grace: 0
  hero_of_the_village: 0

  slowness: 0
  weakness: 0
  bad_luck: 0